# Use old ubuntu image as a workarount to Tango DS launch problems
group: deprecated-2017Q4

language: python

python:
  - 3.6

sudo: required

services:
  - docker

env:
  global:
    - secure: "CCVtBQ8xIrOwUJGXxd81wyD1ng72Hf6d9y2U+5X88aVGTrOa8/hut10C+Jmnyf0NTZmGh/49eVvoWRvLDhjpECFMuO/bLkiNtVjz0VtWAHT2W98QJYmeymPzx86tGa+iAZCwlgXeRQFJCw1eqQvBYnjumMZWb9kj3fqgpqpSRH5SWnuRCmbxOoelmtTTUC8YKkzasAHYs03faR0DCq0oBmDy9nU2cfcRN7oE5wXUfEnDwNaoHbiQA4wiJbzNpBV432bIDtzD7gsFdiIT6ExJVFHi1gWB32bGZdbiDPpej7I2fW5qunbzUXS5doVhoBU67qqhI241RJ+AOBVb+sQnF8gwwi9/5/mcORiSBX7yI59YsOXYwo2YW+8PGr3OlF3t0+z92Q3uPytUXysdtVO4dExnLbV8OEzgmWCkv2M3GIajjE3isYAaBItqSBJHJnRClza4nNg2WLwmqLPBgM4AuSUZEpB/8kbz9kTecVEb13WrlTCNc8KVRGR+EGa4KmWADwOOxurxeb/NsTteOnzdyfrP2TXKeGOkN2uqBGYJaI7OoefsgLG7VF/+Sz4MTETMs/gZojwpO6igKBS1sJlcXujz/kt125b8gcSnrAiU1TjbZIBew/D40H64tpBcuk+dqF6i6HCoV2QmZ1QEpHOSoDk9FEaKMlgKhQj59/cWcI8="

  matrix:
  - DOCKER_IMG=cpascual/taurus-test:debian-jessie
  - DOCKER_IMG=cpascual/taurus-test:debian-stretch
  - DOCKER_IMG=cpascual/taurus-test:debian-buster

matrix:
    allow_failures:
        - env: DOCKER_IMG=cpascual/taurus-test:debian-jessie
        - env: DOCKER_IMG=cpascual/taurus-test:debian-buster

before_install:
  - docker run -d --name=taurus-test -h taurus-test --volume=`pwd`:/taurus $DOCKER_IMG
  - sleep 10
  
script:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - set -e
  - docker exec -t taurus-test /bin/bash -c "cd /taurus ; python setup.py install"
  - docker exec -t taurus-test /bin/bash -c "TAURUS_STARTER_WAIT=5 taurustestsuite -e 'taurus\.core\.util\.test\.test_timer'"
  - docker exec -t taurus-test /bin/bash -c "cd /taurus ; sphinx-build -qW doc/source/ build/sphinx/html"
  # deploy sphinx-built docs to taurus-doc repo
  - if [[ "$DOCKER_IMG" == "cpascual/taurus-test:debian-stretch" && "$TRAVIS_REPO_SLUG" == "taurus-org/taurus" ]]; then
      pip install doctr ;
      docker exec taurus-test /bin/bash -c "touch /taurus/build/sphinx/html/.nojekyll" ;
      if [[ "${TRAVIS_BRANCH}" == "develop" ]]; then
        doctr deploy . ;
      else
        doctr deploy "v-$TRAVIS_BRANCH"  ;
      fi;
    fi

doctr:
  key-path : ci/github_deploy_key.enc
  deploy-repo : taurus-org/taurus-doc
  require-master: false
  sync: true
  built-docs: build/sphinx/html/
